const ActivityName = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CREATE_USER: "CREATE_USER",
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    DELETE_USER: "DELETE_USER",
    DELETE_PROJECT: "DELETE_PROJECT",
    VIEW_PROJECT: "VIEW_PROJECT",
    VIEW_USER: "VIEW_USER",
    UPLOAD: "UPLOAD",
    DOWNLOAD: "DOWNLOAD",
    ERROR: "ERROR",
  };
  
  